cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ziyan.gao19@gmail.com:
      email: ziyan.gao19@gmail.com
      name: ZIYAN GAO
      password: $2b$12$cR0HIEoFIAMy41J0FwZAWuvLVYhXP8PIzlVa9aEpX.dw4IwIPEhFK
    p.nardviriyakul20@gmail.com:
      email: p.nardviriyakul20@gmail.com
      name: PASAVICH NARDVIRIYAKUL
      password: $2b$12$pQbPSCtql4E.urIqoqBoPeCk9ExQzXK5ySwrdz03MsX1/epapYiLi
    yifan.chen20@gmail.com:
      email: yifan.chen20@gmail.com
      name: YIFAN CHEN
      password: $2b$12$OoIrynTHD8LqB5MiKO9oQuNBpmE7uTTNG0J/ZRb3lrmWKPNkSA/yS
    wei.chen@gmail.com:
      email: wei.chen@gmail.com
      name: WEI CHEN
      password: $2b$12$ztWBc.e5wPnCUksq4lMGSOzYIt5DpBKaz2jZoA8ilArZ190kfp0fC
    admin:
      email: admin
      name: ADMIN ADMIN
      password: $2b$12$rMI7Hc.452rIHj96DOtCG.cFSBrAhFet/DnWdrVBsB3nvawKwdQL2
preauthorized:
  emails:
  - fei.liu.csu@gmail.com
